### ISSUE TITLE
document how to build GENESIS from source in the RadiaSoft container

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#114]

**Comment by bruhwile** [comment]
The build process is documented in the following script:
   https://github.com/radiasoft/radtrack/blob/master/install/genesis/build_genesis.sh 

Note: this grabs version 2 of GENESIS from the official website. This is *not* the new version 3. Also, it is not the version from Argonne that supports SDDS. I haven't figured out how to build that version.

Also note: the script builds GENESIS both in serial and in parallel. And it grabs all the example input files.

**Comment by bruhwile** [comment]
This is how I installed the serial and parallel executables inside my VM.
The name 'gen_build_test' is not general -- this is the name of the directory where I ran the shell script referenced above.

[src;@bsim gen_build_test]$ su -
Password: 
~# cp /home/vagrant/gen_build_test/genesis/genesis /usr/bin/
~# cp /home/vagrant/gen_build_test/genesis_mpi/genesis_mpi /usr/bin/
~# chmod a+rx /usr/bin/genesis
~# chmod a+rx /usr/bin/genesis_mpi 
~# exit
logout
[src;@bsim gen_build_test]$


Note that the su password inside the VM is 'vagrant' unless you set it to something else.

**Comment by bruhwile** [comment]
Once it is installed, you can run GENESIS in serial simply by typing 'genesis' at the command line.
It prompts you for an input file.
If you are in .../examples/visa/ then you can just type 'visa.in'

To run GENESIS without interactive prompting, you have to create a file that lists the names of all the files that you would otherwise enter manually at the prompt. For the example above, you can create a file named 'file_list.txt' which contains the single line of text 'visa.in'

Then you can run GENESIS like this:
$ genesis < file_list.txt > visa_out.txt 2> visa_err.txt

stdout will be written to the file visa_out.txt
stderr will be written to the file visa_err.txt
You can optionally choose to run GENESIS in the background.

Interactive prompts also work when running in parallel.
Just do the following for use of 2 processors:
$ mpirun -np 2 genesis_mpi
and enter 'visa.in' at the prompt.

**Comment by robnagler** [comment]
Thanks for documenting what you did. It helps me for automation.

A few comments:

You don't need to "su -". Rather, you can "sudo" or "sudo su -". Vagrant is
in /etc/sudoers, and vagrant has no password so it's easy to do. (Yes, your
virtual machine is quite insecure.)  sudo is practical for quick commands
as root.

If you can avoid it, do not install globally. Rather install in ~/bin or
better yet, install in the bin dir of the virtualenv you are using
"$(VIRTUAL_ENV)/bin". I prefer the latter these days so that you can test
out new versions of code.

To install, you should use the install command:

install -m 755 ~/gen_build_test/genesis/genesis
~/gen_build_test/genesis_mpi/genesis_mpi
"$(VIRTUAL_ENV)/bin"

You should set modes explicitly when installing especially when installing
globally.

BTW, it seems that mpifort should be used instead of mpif77 explicitly. I
think mpifort will always find the right compiler and libraries.

Rob

**Comment by bruhwile** [comment]
Thanks for the info on the right way of installing software and using sudo
in the container!
David

**Comment by qedseung** [comment]
Hello,
Thanks, I was able to try out genesis, but I didn't see outputs, this is
all I saw:

Genesis_Current$ ./genesis
-------------------------------
Genesis 1.3 has begun execution
(Version 1.0 Unix)

Please enter input file name
visa.in
Slice     1: Simulation  10% completed.
Slice     1: Simulation  20% completed.
Slice     1: Simulation  30% completed.
Slice     1: Simulation  40% completed.
Slice     1: Simulation  50% completed.
Slice     1: Simulation  60% completed.
Slice     1: Simulation  70% completed.
Slice     1: Simulation  80% completed.
Slice     1: Simulation  90% completed.
Slice     1: Simulation 100% completed.
***  writing history record for slice     1
***  closing files

Genesis run has finished

On Tue, Jun 30, 2015 at 8:46 AM, David Bruhwiler <notifications@github.com>
wrote:

> Thanks for the info on the right way of installing software and using sudo
> in the container!
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/114#issuecomment-117234346>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845
