### ISSUE TITLE
Abstract and refactor all os.system calls

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#12]
Modules like BPsdds2srw need an abstraction to call sddsanalyzebeam, etc.

**Comment by bruhwile** [comment]
Can this ticket be closed?

**Comment by robnagler** [comment]
I don't think so.

Rob

**Comment by MZHarrison** [comment]
Would this be solved by replacing os.system() with QProcess.start()?

Also, BPsdds2srw isn't used anywhere in RadTrack. Since it's the only module using os.system(), this issue may be solved by just deleting it.

**Comment by robnagler** [comment]
I think it needs to be a QProcess. We should be able to timeout simulations and end them with a button. All simulations should be run with external processes so that they can be started, say, with mpiexex, and so they can be decoupled from the particular python version that RT is using.

**Comment by MZHarrison** [comment]
Currently, Elegant and Genesis are run in `QProcess` instances. The remaining simulation code is SRW. If I'm reading `srw_controller.py` and `srwlib.py` correctly, then SRW is run as Python function calls instead of external programs. To get the same control as a `QProcess`, use a call to [`QtConcurrent.run()`](http://doc.qt.io/qt-4.8/qtconcurrentrun.html) and use the returned [`QFuture`](http://doc.qt.io/qt-4.8/qfuture.html) object to control the process (monitor progress, abort, etc.).

**Comment by robnagler** [comment]
SRW shouldn't be run as a library, but as a separate process. The script
should be written and then run like elegant or genesis. This would allow
more code sharing and standardize the UI.

The idea behind this ticket is to generalize the code into a module that
does the calls to QProcess and perhaps helps integrate the UI elements.
Right now that codes is copied into genesis_controller from RbEle.

**Comment by MZHarrison** [comment]
Nothing in RadTrack uses os.system() for external processes. Closing.
