### ISSUE TITLE
enumerated non-integer values genesis

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#123]
F1ST and FBESS0 are enumerated types but some of the options are represented by non-integer values, 0.5 and a Bessel Function respectively

**Comment by robnagler** [comment]
We could relax the restriction that it must be an int. There isn't a lot
that's connected to the type. Could assert that the type has an __cmp__
function, which is all that's needed from rt_enum's perspective.

It can't be a str, because from_anything looks at the type to know how to
do the conversion. well, I guess it could be flexible in the way it does
the lookup, but it would yield inconsistent results. Look at
from_anything()'s impl.

Rob
