### ISSUE TITLE
Elegant tab needs better error messages

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#137]
*Email from user:*

Is there some way to visualize errors from failed simulations inside RadTrack? For instance, if ELEGANT fails because I forget to populate one of the Quad parameters I simply get told Simulation failed with errors. How do I find these errors from within RadTrack?

![screen shot 2015-12-08 at 14 00 13](https://cloud.githubusercontent.com/assets/10423990/11670576/7aa583f2-9db7-11e5-8e47-a8b099983753.png)

**Comment by MZHarrison** [comment]
David, could you ask Christina to send the LTE file that causes Elegant to fail? She can also just describe the beam line that was created in the Elegant tab. I've tried a completely blank beam line shown below and Elegant didn't return any errors.

```
! This Elegant file was created by RadTrack
! RadTrack (c) 2013, RadiaSoft, LLC

X1:  DRIF
Q:  QUAD
B:  LINE=(X1, Q)

RETURN
```

**Comment by bruhwile** [comment]
I've forwarded the request to Christina.

David

**Comment by shaftan** [comment]
Mark, David,

I think I made an example where you can stop general output from Elegant and pipe out only "milestone" and error messages. Is this something that you are looking for?
Timur.


--------------------------------------------
On Tue, 12/8/15, Mark Harrison <notifications@github.com> wrote:

 Subject: [radtrack] Elegant tab needs better error messages (#137)
 To: "radiasoft/radtrack" <radtrack@noreply.github.com>
 Date: Tuesday, December 8, 2015, 5:25 PM
 
 Is there some way to visualize
 errors from failed simulations inside RadTrack? For
 instance, if ELEGANT fails because I forget to populate one
 of the Quad parameters I simply get told Simulation failed
 with errors. How do I find these errors from within
 RadTrack?
 
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by MZHarrison** [comment]
Commit referenced above should give more information about why Elegant stopped in the case of crashing or other irregular stoppage. As a last resort, this tab writes to two files: `elegant_output.txt` and `elegant_errors.txt`, which may help diagnose the problem.

**Comment by MZHarrison** [comment]
Given the number of changes since this issue report and the lack of response, I'm closing this issue since any problems are different by now.
