### ISSUE TITLE
implement Timur's progress bar on the Elegant tab

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#54]

**Comment by bruhwile** [comment]
Assigning this to Mark, because he is already thinking about closely related issues.

**Comment by MZHarrison** [comment]
Timur's program (https://gist.github.com/bruhwile/07fb33d77faaf24215d4) doesn't track the progress of an Elegant simulation, only when it starts and stops. I've created a new gist to show the output from an example run with 4,000,000 particles: https://gist.github.com/MZHarrison/ad0c20fd8faee9fc2812

The run time is given in seconds along the left. Notice the jump of 18 seconds from line 141 to line 142. The entire Elegant simulation happens between those two lines. There is no intermediate progress reported.

I'm thinking that monitoring an Elegant simulation is impossible since there is no console output while it is running. Elegant only outputs the simulation settings (essentially a copy of the input files) and a summary of the results after the simulation completes.

**Comment by MZHarrison** [comment]
Progress bar implemented in commit 5937bb58d3eedb694fd17eb7f4467ebfe31ea5a0.
