### ISSUE TITLE
run through use cases on MacOS

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#70]
Stephen and Gerard should both do this on Tuesday or on Wednesday morning.

This assumes that a VM-contained version of RadTrack is working on the Mac by this time.

There should be three use cases ready by the end of Monday:
  1) FODO
  2) something new from Gerard
  3) laser heater with Elegant, from David

**Comment by sdwebb** [comment]
I just tried to run the FODO cell using a bunch and beamline with the tab. When I go to use Elegant I get the following Pythonic error:

```
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/RbEle.py", line 147, in simulate
    self.parent.tabWidget.widget(index).widget().saveToSDDS(bunchFileName)
  File "/home/vagrant/src/radiasoft/radtrack/radtrack/BunchTab.py", line 1440, in saveToSDDS
    mySDDS.save(sddsFileName)
  File "/home/vagrant/Envs/py2/lib/python2.7/site-packages/sdds.py", line 136, in save
    rows = len(self.columnData[0][page])
TypeError: object of type 'numpy.float64' has no len()
```
Otherwise, the installer went off without a hitch and everything was all good. The source code for that error is actually in radtrack/install/fedora and it seems that the bunch tab is generating numpy arrays, which don't respond well to the len() command.

**Comment by robnagler** [comment]
Right. This is issue #72, which I just reopened.

I believe there is a newer version of SDDSPython on Linux than on Windows.

Rob
