### ISSUE TITLE
implement a test to execute one standard Elegant example

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#84]
First run the example from the command line and document it as a use case.
Then implement a test.

**Comment by bruhwile** [comment]
Some info from Rob regarding the Python testing infrastructure:

One can run:
> python setup.py test
or
> py.test

or an individual test:
> cd tests/genesis
> py.test lattice_file_test.py

If you want to work in Linux from your Mac or Windows desktop, Rob has setup a development environment in the vagrant VM that gets downloaded. In this VM, when using emacs, one can do the following when editing a test:
> \C-c \C-m

This will prompt to run:
Compile command: py.test lattice_file_test.py

Hit return, and the test will run. This makes it very easy to run tests within emacs.

**Comment by MZHarrison** [comment]
Currently, in radtrack/tests/elegant/importExport_test.py, each of the .lte files in radtrack/deprecated/elegant/beamlines/ is:

1. Imported into RadTrack (without the GUI)
2. Exported to another file
3. This exported file is imported into RadTrack to make sure it generates the same elements as the original .lte file.
3. The exported file is run through an Elegant simulation with radtrack/deprecated/elegant/bunches/elegantSimTest.sdds.

These tests don't look at the results; they only make sure that Elegant runs without errors. If a lattice files with appropriate bunch files could be generated, they could be used instead of the random assortment currently used. Then, the results of the simulations could be properly tested against expected results.
