### ISSUE TITLE
develop python code to emulate IDL code from XGenesis

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#9]
Once working code is in place, it will then be integrated within the Genesis tab

**Comment by sdwebb** [comment]
Current status: I am trying to generalize the parsing of the ASCII output to deal with variations in LOUT flag in the Genesis .in file. Steve Seung successfully read in a particle file generated by the SDDS Genesis in the Data Viz tab, so that is a big step there (attached figure for evidence). I could not get this to work on Linux using RadTrack through an X tunnel.

![untitled](https://cloud.githubusercontent.com/assets/7430829/6814106/6181c4fe-d241-11e4-8371-4486c56e23b0.png)

**Comment by qedseung** [comment]
Yeah I had to go through PC, data visualization (more specifically
servicelib.py) uses the sddsdata.pyd to organize the data from a sdds file.

On Tue, Mar 24, 2015 at 3:18 PM, Stephen Webb <notifications@github.com>
wrote:

> Current status: I am trying to generalize the parsing of the ASCII output
> to deal with variations in LOUT flag in the Genesis .in file. Steve Seung
> successfully read in a particle file generated by the SDDS Genesis in the
> Data Viz tab, so that is a big step there (attached figure for evidence). I
> could not get this to work on Linux using RadTrack through an X tunnel.
>
> [image: untitled]
> <https://cloud.githubusercontent.com/assets/7430829/6814106/6181c4fe-d241-11e4-8371-4486c56e23b0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/9#issuecomment-85716388>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by sdwebb** [comment]
Hi Steve,

I’ve sent another file by Dropbox. Could you see what the Data Viz. tab does to field data?

It is a 2.5 GB file for a time-dependent simulation. It would be very good to see what exactly is going to happen there.

--
Stephen Webb, PhD
Research Scientist
RadiaSoft, LLC.

e: swebb@radiasoft.net
www.radiasoft.net

**Comment by MZHarrison** [comment]
Closed by commits 7ad6e38d05e22233ba28a38dd740510d2150f6b2, 9b3b1376fba1f10822f5df304d0672eca7a53e87, 01321ca6f3eeb1209e41c20cc16fc9a446354d90,
and 5d61b670f6a9ac680518fa5a2c586d98c4708934.
